//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTEvKontrol.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evkontrolEntities : DbContext
    {
        public evkontrolEntities()
            : base("name=evkontrolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cihazlar> Cihazlar { get; set; }
        public virtual DbSet<Ev> Ev { get; set; }
        public virtual DbSet<Oda> Oda { get; set; }
        public virtual DbSet<Sistem> Sistem { get; set; }
    }
}
