//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTEvKontrol.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oda()
        {
            this.Sistem = new HashSet<Sistem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EvID { get; set; }
        public Nullable<int> CihazID { get; set; }
        public string OdaAdi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Cihazlar Cihazlar { get; set; }
        public virtual Ev Ev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sistem> Sistem { get; set; }
    }
}
